[project]
name = "open-notebook"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "datalad>=1.3.1",
    "ipython>=9.10.0",
    "jupyter>=1.1.1",
    "jupyter-cache>=1.0.1",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
]
